import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
const fcl = require("@onflow/fcl");


async function lol() {
  fcl
  .config()
  .put("accessNode.api", "https://access-testnet.onflow.org");
var response =  await fcl.send([
    fcl.script`
      pub fun main(): Int {
        return 1 + 2
      }
    `
  ])
  
  var data =  await fcl.decode(response)
  console.log(data) // 3
  
    
}
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        

      

        <div className={styles.grid}>
          
        <button
        onClick={lol}
        >
          clikome
        </button>
          
        </div>
      </main>

      
        
      
    </div>
  )
}
